version: '3'
services:

  mysql:
    image: "mariadb:10"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "insider4dev"
      MYSQL_DATABASE: "insider_dev"

  redis:
    image: "redis:4"
    ports:
      - "6379:6379"

